const Data = () => {
  [
      { id: 1,
        category: "Living Room",
        products: [ 
        {
          name: "Nepal Sofa Set",
          image: ["https://baffihomeng.com/cdn/shop/files/nepal-sofa-set.jpg?v=1742035247", "https://baffihomeng.com/cdn/shop/files/nepal-sofa-set-2.jpg?v=1742035246", "https://baffihomeng.com/cdn/shop/files/nepal-sofa-set-4.jpg?v=1742035247", "https://baffihomeng.com/cdn/shop/files/nepal-sofa-set-8.jpg?v=1742035247"],
          description:"The Sofa comes with 4+3+1 Seaters,It also comes with optional Center Table, TV stand, Side stool and Showglass",
          comment: ["the chair is so commfortable", "i love this", "this is amazing", "i love the color"],
          review: ["5 star", "4.5 star", "4 star"],
          pricing: "₦11,800,000.00",
          deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE.All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer.Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",
        },

          {
          name: "Lisbon Corner Set",
          image: ["https://baffihomeng.com/cdn/shop/files/Lisbon-Corner-Set.jpg?v=1737630578", "https://baffihomeng.com/cdn/shop/files/Lisbon-Corner-Set-1.jpg?v=1738072331", "https://baffihomeng.com/cdn/shop/files/Lisbon-Corner-Set-3.jpg?v=1738072331"],
          description: "A stylish sectional sofa, upholstered in soft, plush fabric. It includes a five-seater, a three-seater, and a single accent chair, offering versatile seating options. Designed for a modern living room, the set features sleek silhouettes, and neutral tones that blend seamlessly with contemporary décor which makes it a functional yet elegant piece for any modern space.",
          comment: ["the chair is so commfortable", "i love this", "this is amazing", "i love the color"],
          review: ["5 star", "4.5 star", "4 star"],
          pricing: "₦13,060,000.00",
          deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",
        },

        { 
          name:"Asel Sofa Set",
          image:["https://baffihomeng.com/cdn/shop/files/Asel-sofa-set.jpg?v=1740830837", "https://baffihomeng.com/cdn/shop/files/Asel-sofa-set-2.jpg?v=1740830837", "https://baffihomeng.com/cdn/shop/files/Asel-sofa-set-4.jpg?v=1740830837", "https://baffihomeng.com/cdn/shop/files/Asel-sofa-set.jpg?v=1740830837"],
          description: "The Combo Package includes: 3+3+1+1 Sofa Set",
          comment:["the chair is so commfortable", "i love this", "this is amazing", "i love the color"],
          review: ["5 star", "4.5 star", "4 star"],
          pricing: "₦8,900,000.00",
          deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

        },
          { 
          name: "Berlin modern Sofa Set",
          image:["https://baffihomeng.com/cdn/shop/files/berlinmodernsofaset.jpg?v=1742039720", "https://baffihomeng.com/cdn/shop/files/berlin-modern-sofa-set-2.jpg?v=1742039720", "https://baffihomeng.com/cdn/shop/files/berlin-modern-sofa-set-3.jpg?v=1742039720"],
          description:"The set comes with 3+3+1+1 seaters",
          comment:["the chair is so commfortable", "i love this", "this is amazing", "i love the color"],
          review:["5 star", "4.5 star", "4 star"],
          pricing:"₦10,900,000.00",
          deliveryAndInstallation:"All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

        },

          { 
          name:"Milano L-shape",
          image:["https://baffihomeng.com/cdn/shop/files/Milano-L-shape-3.jpg?v=1728993375", "https://baffihomeng.com/cdn/shop/files/Milano-L-shape-1.jpg?v=1728993375", "https://baffihomeng.com/cdn/shop/files/Milano-L-shape-2.jpg?v=1728993375"],
          description:"Milano L-Shape is a stylish and modern L-shaped sofa designed to maximize seating space while adding a sleek touch to any living room. It's perfect for lounging, entertaining guests, or relaxing with family.",
          comment:["the chair is so commfortable", "i love this", "this is amazing", "i love the color"],
          review:["5 star", "4.5 star", "4 star"],
          pricing: "₦1,400,000.00",
          deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

      },
      {
          name:"Prestige Sofa Set",
          image:["https://baffihomeng.com/cdn/shop/files/still-sofa-set.jpg?v=1737995060", "https://baffihomeng.com/cdn/shop/files/still-sofa-set-2.jpg?v=1737995060"],
          description:"The set come with 3+3+1+1 seater. The center table is NOT included in the set. The 3 seaters back rest can be adjusted to a sofa bed. The fabric is made with Turkish Nubuck which is easy to clean and maintain. The skeleton is made of trated hornbeam wood. Soft foam with comfortable seating. You can clean using soft towel and can be washed using upholstery machine.",
          comment:["the chair is so commfortable", "i love this", "this is amazing", "i love the color"],
          review:["5 star", "4.5 star", "4 star"],
          pricing: "₦9,625,000.00",
          deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

      }, 
      {
          name:"Mustang Sofa Set",
          image:["https://baffihomeng.com/cdn/shop/files/mustang-sofa-set.jpg?v=1747304997", "https://baffihomeng.com/cdn/shop/files/mustang-sofa-set-1.jpg?v=1747304997"],
          description:"The set come with 3+3+1+1 seaters. The center table is NOT included in the set. The 3 seaters back rest can be adjusted to a sofa bed. The fabric is made with Turkish Nubuck which is easy to clean and maintain. The skeleton is made of trated hornbeam wood. Soft foam with comfortable seating. You can clean using soft towel and can be washed using upholstery machine.",
          comment:["the chair is so commfortable", "i love this", "this is amazing", "i love the color"],
          review:["5 star", "4.5 star", "4 star"],
          pricing: "₦9,720,000.00",
          deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",
      }
    ],
    },
      { id: 2,
        category: "Bed Room",
        products: [
         { name: "Alina Bedroom Set",
          pricing: "₦6,750,000.00",
          description: "Transform your bedroom into a luxurious retreat with the Alina Bedroom Set. Crafted to blend elegance with functionality, this set offers everything you need to create a stylish and organized space. From the comfortable bed base to the spacious wardrobe, each piece is designed with meticulous attention to detail. Let’s delve into the features that make the Alina Bedroom Set a perfect choice for your home.",
          image: ["https://baffihomeng.com/cdn/shop/files/2600.jpg?v=1720192423", "https://baffihomeng.com/cdn/shop/files/2599.jpg?v=1720192423"],
          tags: ["Bestsellers"],
          additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
          features: ["Sleek and Timeless Design: The Alina Bedroom Set features a sleek and timeless design that effortlessly complements any bedroom decor. With clean lines, subtle accents, and a neutral color palette, this set creates a serene and inviting ambiance that promotes relaxation and rejuvenation.",
          "Spacious Storage Solutions: The set includes a spacious wardrobe and dresser, providing ample storage for your clothing, accessories, and personal items. The wardrobe features multiple compartments and hanging space, while the dresser offers additional drawers for smaller items, keeping your bedroom organized and clutter-free.",
          "Comfortable and Durable Bed Base: The bed base is designed for comfort and durability, ensuring a restful night's sleep. It features a sturdy frame and high-quality materials that provide excellent support, while the plush mattress offers the perfect balance of softness and firmness for a rejuvenating sleep experience.",
          "Versatile and Functional: The Alina Bedroom Set is versatile and functional, making it suitable for various bedroom sizes and styles. Whether you have a spacious master bedroom or a cozy guest room, this set adapts to your needs, providing both style and practicality.",
          "Easy Maintenance: The materials used in the Alina Bedroom Set are easy to clean and maintain, ensuring that your bedroom remains looking fresh and inviting. The surfaces are resistant to stains and scratches, allowing you to enjoy your furniture for years to come."],
          comment: ["Products are very good, I am very happy with the quality and the price.",
          "The Alina Bedroom Set has transformed my bedroom into a luxurious retreat. The design is sleek and timeless, and the storage solutions are perfect for keeping everything organized. Highly recommend!"],
          review:["5 star", "4.5 star", "4 star"],
          deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",
          },
          
          {
            name: "Bianca Bedroom Set",
            comment:["Products are very good, I am very happy with the quality and the price.",
            "The Bianca Bedroom Set has transformed my bedroom into a luxurious retreat. The design is sleek and timeless, and the storage solutions are perfect for keeping everything organized. Highly recommend!"],
            description: "Our Bianca bedroom set is crafted from the highest quality materials, featuring a stunning wardrobe, exquisite Bed Frame, magnificent Dresser, stylish Dresser Mirror, and a chic Nightstand.",
            image: ["https://baffihomeng.com/cdn/shop/files/2332.jpg?v=1720195340", "https://baffihomeng.com/cdn/shop/files/2333.jpg?v=1720195340", "https://baffihomeng.com/cdn/shop/files/2334.jpg?v=1720195340"],
            review:["5 star", "4.5 star", "4 star"],
            pricing: "₦5,550,000.00",
            tags: ["Bestsellers, Promo"],
            additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
            features: [ "Our Bianca bedroom set is crafted from the highest quality materials, featuring a stunning wardrobe, exquisite Bed Frame, magnificent Dresser, stylish Dresser Mirror, and a chic Nightstand. With its sophisticated, contemporary design, this bedroom set will surely add a touch of luxury to any bedroom space.",
            "The solid construction ensures this bedroom set is both beautiful and built to last. It comes in an elegant finish, providing a slightly glamorous contrast. Matching bedding and curtains will complete the look, making it even more stylish and modern. Additionally, all pieces have ample storage compartments, allowing you to organize and store your items quickly."],
            deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",
          },
  
          {
              name: "Golf Bedroom Set",
              pricing: "₦8,550,000.00",
              description: "Transform your bedroom into a luxurious retreat with the Alina Bedroom Set. Crafted to blend elegance with functionality, this set offers everything you need to create a stylish and organized space. From the comfortable bed base to the spacious wardrobe, each piece is designed with meticulous attention to detail. Let’s delve into the features that make the Alina Bedroom Set a perfect choice for your home.",
              image: ["https://baffihomeng.com/cdn/shop/files/2156.jpg?v=1720195568", "https://baffihomeng.com/cdn/shop/files/2157.jpg?v=1720195568"],
              tags: ["Bestsellers"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              features: ["Sleek and Timeless Design: The Alina Bedroom Set features a sleek and timeless design that effortlessly complements any bedroom decor. With clean lines, subtle accents, and a neutral color palette, this set creates a serene and inviting ambiance that promotes relaxation and rejuvenation.","Spacious Storage Solutions: The set includes a spacious wardrobe and dresser, providing ample storage for your clothing, accessories, and personal items. The wardrobe features multiple compartments and hanging space, while the dresser offers additional drawers for smaller items, keeping your bedroom organized and clutter-free.","Comfortable and Durable Bed Base: The bed base is designed for comfort and durability, ensuring a restful night's sleep. It features a sturdy frame and high-quality materials that provide excellent support, while the plush mattress offers the perfect balance of softness and firmness for a rejuvenating sleep experience.","Versatile and Functional: The Alina Bedroom Set is versatile and functional, making it suitable for various bedroom sizes and styles. Whether you have a spacious master bedroom or a cozy guest room, this set adapts to your needs, providing both style and practicality.","Easy Maintenance: The materials used in the Alina Bedroom Set are easy to clean and maintain, ensuring that your bedroom remains looking fresh and inviting. The surfaces are resistant to stains and scratches, allowing you to enjoy your furniture for years to come."],
              comment: ["Products are very good, I am very happy with the quality and the price.",
                "The Alina Bedroom Set has transformed my bedroom into a luxurious retreat. The design is sleek and timeless, and the storage solutions are perfect for keeping everything organized. Highly recommend!" ],
              deliveryAndInstallation: ["All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer."],
                },
            {
              name: "Atlantis Bedroom Set",
              pricing:"₦10,700,660.00",
              description: "Transform your bedroom into a luxurious retreat with the Alina Bedroom Set. Crafted to blend elegance with functionality, this set offers everything you need to create a stylish and organized space. From the comfortable bed base to the spacious wardrobe, each piece is designed with meticulous attention to detail. Let’s delve into the features that make the Alina Bedroom Set a perfect choice for your home.",
              image: ["https://baffihomeng.com/cdn/shop/files/1702.jpg?v=1720196476", "https://baffihomeng.com/cdn/shop/files/1704.jpg?v=1720196476"],
              tags: ["Bestsellers"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["Products are very good, I am very happy with the quality and the price.",
              "The Alina Bedroom Set has transformed my bedroom into a luxurious retreat. The design is sleek and timeless, and the storage solutions are perfect for keeping everything organized. Highly recommend!"],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

            },
            {
              name: "Perla Bedroom Set",
              pricing: "₦7,950,660.00",
              description: "Transform your bedroom into a luxurious retreat with the Alina Bedroom Set. Crafted to blend elegance with functionality, this set offers everything you need to create a stylish and organized space. From the comfortable bed base to the spacious wardrobe, each piece is designed with meticulous attention to detail. Let’s delve into the features that make the Alina Bedroom Set a perfect choice for your home.",
              image: ["https://baffihomeng.com/cdn/shop/files/2306.jpg?v=1720195390", "https://baffihomeng.com/cdn/shop/files/2307.jpg?v=1720195390"],
              review:["5 star", "4.5 star", "4 star"],
              tags: ["Bestsellers"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["Products are very good, I am very happy with the quality and the price.",
              "The Alina Bedroom Set has transformed my bedroom into a luxurious retreat. The design is sleek and timeless, and the storage solutions are perfect for keeping everything organized. Highly recommend!"],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",
            },

            {
              name: "Jumbo Bedroom Set",
              pricing: "₦5,750,660.00",
              description: "Transform your bedroom into a luxurious retreat with the Alina Bedroom Set. Crafted to blend elegance with functionality, this set offers everything you need to create a stylish and organized space. From the comfortable bed base to the spacious wardrobe, each piece is designed with meticulous attention to detail. Let’s delve into the features that make the Alina Bedroom Set a perfect choice for your home.",
              image: ["https://baffihomeng.com/cdn/shop/files/2968.jpg?v=1720191706", "https://baffihomeng.com/cdn/shop/files/2969.jpg?v=1720191706"],
              review:["5 star", "4.5 star", "4 star"],
              tags: ["Bestsellers"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["Products are very good, I am very happy with the quality and the price.",
              "The Alina Bedroom Set has transformed my bedroom into a luxurious retreat. The design is sleek and timeless, and the storage solutions are perfect for keeping everything organized. Highly recommend!"],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",
            },
            {
              name: "Magnum Bedroom Set",
              pricing: "₦7,450,660.00",
              description: "Transform your bedroom into a luxurious retreat with the Alina Bedroom Set. Crafted to blend elegance with functionality, this set offers everything you need to create a stylish and organized space. From the comfortable bed base to the spacious wardrobe, each piece is designed with meticulous attention to detail. Let’s delve into the features that make the Alina Bedroom Set a perfect choice for your home.",
              image: ["https://baffihomeng.com/cdn/shop/files/1089.jpg?v=1747305617", "https://baffihomeng.com/cdn/shop/files/1094.jpg?v=1747305617"],
              tags: ["Bestsellers"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["Products are very good, I am very happy with the quality and the price.",
              "The Alina Bedroom Set has transformed my bedroom into a luxurious retreat. The design is sleek and timeless, and the storage solutions are perfect for keeping everything organized. Highly recommend!"],
              deliveryAndInstallation: [ "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer."],

            },
            {
              name: "Brownie Bedroom Set",
              pricing: "₦6,750,660.00",
              description: "Transform your bedroom into a luxurious retreat with the Alina Bedroom Set. Crafted to blend elegance with functionality, this set offers everything you need to create a stylish and organized space. From the comfortable bed base to the spacious wardrobe, each piece is designed with meticulous attention to detail. Let’s delve into the features that make the Alina Bedroom Set a perfect choice for your home.",
              image: ["https://baffihomeng.com/cdn/shop/files/770.jpg?v=1720198196", "https://baffihomeng.com/cdn/shop/files/775.jpg?v=1720198196"],
              tags: ["Bestsellers"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["Products are very good, I am very happy with the quality and the price.",
              "The Alina Bedroom Set has transformed my bedroom into a luxurious retreat. The design is sleek and timeless, and the storage solutions are perfect for keeping everything organized. Highly recommend!"],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

            },

            {
              name: "Wooden Bedroom Set",
              pricing: "₦16,850,000.00",
              description: "Transform your bedroom into a luxurious retreat with the Alina Bedroom Set. Crafted to blend elegance with functionality, this set offers everything you need to create a stylish and organized space. From the comfortable bed base to the spacious wardrobe, each piece is designed with meticulous attention to detail. Let’s delve into the features that make the Alina Bedroom Set a perfect choice for your home.",
              image: ["https://baffihomeng.com/cdn/shop/files/2791.jpg?v=1738682614", "https://baffihomeng.com/cdn/shop/files/2793.jpg?v=1738682614"],
              tags: ["Bestsellers"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["Products are very good, I am very happy with the quality and the price.",
              "The Alina Bedroom Set has transformed my bedroom into a luxurious retreat. The design is sleek and timeless, and the storage solutions are perfect for keeping everything organized. Highly recommend!"],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

            },
            
            {
              name: "Olimpos Bedroom Set",
              price: "₦6,750,000.00",
              description: "Transform your bedroom into a luxurious retreat with the Alina Bedroom Set. Crafted to blend elegance with functionality, this set offers everything you need to create a stylish and organized space. From the comfortable bed base to the spacious wardrobe, each piece is designed with meticulous attention to detail. Let’s delve into the features that make the Alina Bedroom Set a perfect choice for your home.",
              image: ["https://baffihomeng.com/cdn/shop/files/talya-bed-set.jpg?v=1747301890","https://baffihomeng.com/cdn/shop/files/talya-bed-set-3.jpg?v=1747301890"],
              tags: ["Bestsellers"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["Products are very good, I am very happy with the quality and the price.",
              "The Alina Bedroom Set has transformed my bedroom into a luxurious retreat. The design is sleek and timeless, and the storage solutions are perfect for keeping everything organized. Highly recommend!"],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

          },
        ]
      },
        
          
          { id: 3,
            category: "Dinning Set",
            products: [
                {name: "Monet Dining Set",
              pricing: "₦4,550,000.00",
              description: "Monet Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences.",
              image: ["https://baffihomeng.com/cdn/shop/files/nepal-dining-set.jpg?v=1742037771", "https://baffihomeng.com/cdn/shop/files/nepal-dining-set-2.jpg?v=1742037770"],
              tags: ["Bestsellers"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["This Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

            },
            {
              name: "Shine Dining Set",
              pricing: "₦3,250,000.00",
              description: "Monet Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences.",
              image: ["https://baffihomeng.com/cdn/shop/files/mustang-dining-set.jpg?v=1747304997", "https://baffihomeng.com/cdn/shop/files/mustang-dining-set-2.jpg?v=1747304997"],
              tags: ["Bestsellers"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["This Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",
            },

            {
              name: "Siesta Dining Set",
              pricing: "₦3,000,000.00",
              description: "Monet Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences.",
              image: ["https://baffihomeng.com/cdn/shop/files/siesta-dining-set.jpg?v=1726760403", "https://baffihomeng.com/cdn/shop/files/siesta-dining-set-3.jpg?v=1726760403"],
              tags: ["Bestsellers"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["This Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",
            },

            {
              name: "Bentley Ark Dining Set",
              pricing: "₦3,550,000.00",
              description: "Monet Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences.",
              image: ["https://baffihomeng.com/cdn/shop/files/Petra-Modern-Dining-set.jpg?v=1742048835", "https://baffihomeng.com/cdn/shop/files/Petra-Modern-Dining-set-2.jpg?v=1742048835"],
              tags: ["Bestsellers"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["This Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

            },

            {
              name: "Pedro Dining Set",
              pricing: "₦3,300,000.00",
              description: "Monet Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences.",
              image: ["https://baffihomeng.com/cdn/shop/files/pedro-dining-set.jpg?v=1726759727","https://baffihomeng.com/cdn/shop/files/pedro-dining-set-1.jpg?v=1726759727"],
              tags: ["Bestsellers"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["This Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",


            },

            {
              name: "Godiva Dining Set Black",
              pricing: "₦3,500,000.00",
              description: "Monet Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences.",
              image: ["https://baffihomeng.com/cdn/shop/files/2024.jpg?v=1720195840", "https://baffihomeng.com/cdn/shop/files/2023.jpg?v=1720195840"],
              tags: ["Bestsellers"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["This Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

            },

            {
              name: "Ecrue Dining Set",
              price: "₦2,350,000.00",
              description: "Monet Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences.",
              image: ["https://baffihomeng.com/cdn/shop/files/2780.jpg?v=1720192052","https://baffihomeng.com/cdn/shop/files/2781.jpg?v=1720192052"],
              tags: ["Bestsellers"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["This Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

            },

            {
              name: "Istanbul Maz Dining Set",
              pricing: "₦7,300,000.00",
              description: "Monet Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences.",
              image: ["https://baffihomeng.com/cdn/shop/files/2400.jpg?v=1720195196", "https://baffihomeng.com/cdn/shop/files/2401.jpg?v=1738415572"],
              tags: ["Bestsellers"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["This Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

            },

            {
              name: "San Marino Dining Set",
              pricing: "₦5,340,000.00",
              description: "Monet Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences.",
              tags: ["Bestsellers"],
              image: ["https://baffihomeng.com/cdn/shop/files/2946.jpg?v=1720191762", "https://baffihomeng.com/cdn/shop/files/2945.jpg?v=1738417297"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["This Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

            },

            {
              name: "Tomford Dining Set",
              pricing: "₦6,550,000.00",
              description: "Monet Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences.",
              image: ["https://baffihomeng.com/cdn/shop/files/161.jpg?v=1720199226", "https://baffihomeng.com/cdn/shop/files/162.jpg?v=1720199226"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["This Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",


            },
            
            {
              name: "Venedik Dining Set",
              price: "₦6,250,000.00",
              description: "Monet Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences.",
              image: ["https://baffihomeng.com/cdn/shop/files/246.jpg?v=1720199114", "https://baffihomeng.com/cdn/shop/files/247.jpg?v=1720199114"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["This Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

            },

            {
              name: "Versace Dining Set",
              pricing: "₦5,340,000.00",
              description: "Monet Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences.",
              image: ["https://baffihomeng.com/cdn/shop/files/439.jpg?v=1720198787", "https://baffihomeng.com/cdn/shop/files/444.jpg?v=1720198787"],
              review:["5 star", "4.5 star", "4 star"],
              additionalInformation: "Items Included: Bed base, Commode, Dresser Mirror, Complete Set",
              comment: ["This Dining Set is a masterpiece of luxury, sophistication, and timeless elegance, designed to transform your dining space into an opulent setting. This 8-seater dining set includes a spacious dining table, eight exquisitely crafted chairs, a statement console, and a matching mirror, creating the perfect balance of grandeur and functionality. With premium materials, intricate detailing, and a flawless finish, the Monet Dining Set is an essential choice for high-end interiors and refined dining experiences."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",
            },
          
            ]
          },
            
          { id: 4,
            category: "Kitchen Set ",
            products: [
             { name: "Shine Kitchen Set 101",
              pricing: "₦7,200,000.00",
              description: "Living your kitchen experience to the fullest with this design. making use of all its potential, storage has never been so easy even for those with special space requirements. Spacious volumes and modular units extend the compositional options through geometries in motion that make your kitchen unique",
              image: ["https://baffihomeng.com/cdn/shop/files/1634.jpg?v=1720196705", "https://baffihomeng.com/cdn/shop/files/1635.jpg?v=1720196705"],
              review:["5 star", "4.5 star", "4 star"],
              comment: ["Truly! Storage has never been so easy even for those with special space requirements. Spacious volumes and modular units extend the compositional options through geometries in motion that make your kitchen unique."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",
            },

            {
              category: "Kitchen Set",
              name: "Shine Kitchen Set 102",
              pricing: "₦6,240,000.00",
              description: "Making your kitchen all you want it to be, this design is a perfect blend of functionality and aesthetics. It offers ample storage solutions while maintaining a sleek and modern look. The modular units allow for flexibility in design, ensuring that your kitchen is not only beautiful but also practical.",
              image: ["https://baffihomeng.com/cdn/shop/files/1607.jpg?v=1720196834", "https://baffihomeng.com/cdn/shop/files/1608.jpg?v=1720196834"],
              review:["5 star", "4.5 star", "4 star"],
              comment: ["Truly! Storage has never been so easy even for those with special space requirements. Spacious volumes and modular units extend the compositional options through geometries in motion that make your kitchen unique."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",
            },

            {
              category: "Kitchen Set",
              name: "Shine Kitchen Set 104",
              pricing: "₦6,550,000.00",
              description: "Making your kitchen all you want it to be, this design is a perfect blend of functionality and aesthetics. It offers ample storage solutions while maintaining a sleek and modern look. The modular units allow for flexibility in design, ensuring that your kitchen is not only beautiful but also practical.",
              image: ["https://baffihomeng.com/cdn/shop/files/1624.jpg?v=1720196726","https://baffihomeng.com/cdn/shop/files/1625.jpg?v=1720196726"],
              review:["5 star", "4.5 star", "4 star"],
              comment: ["Truly! Storage has never been so easy even for those with special space requirements. Spacious volumes and modular units extend the compositional options through geometries in motion that make your kitchen unique."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",

            },

            {
                category: "Kitchen Set",
              name: "Shine Kitchen Set 105",
              pricing: "₦6,550,000.00",
              description: "Making your kitchen all you want it to be, this design is a perfect blend of functionality and aesthetics. It offers ample storage solutions while maintaining a sleek and modern look. The modular units allow for flexibility in design, ensuring that your kitchen is not only beautiful but also practical.",
              image: ["https://baffihomeng.com/cdn/shop/files/1629.jpg?v=1720196715", "https://baffihomeng.com/cdn/shop/files/1630.jpg?v=1720196715"],
              review:["5 star", "4.5 star", "4 star"],
              comment: ["Truly! Storage has never been so easy even for those with special space requirements. Spacious volumes and modular units extend the compositional options through geometries in motion that make your kitchen unique."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",


            },
              {
                  category: "Kitchen Set",
              name: "Shine Kitchen Set 106",
              pricing: "₦6,150,000.00",
              description: "Making your kitchen all you want it to be, this design is a perfect blend of functionality and aesthetics. It offers ample storage solutions while maintaining a sleek and modern look. The modular units allow for flexibility in design, ensuring that your kitchen is not only beautiful but also practical.",
              image:["https://baffihomeng.com/cdn/shop/files/1649.jpg?v=1720196676", "https://baffihomeng.com/cdn/shop/files/1650.jpg?v=1720196676"],
              review:["5 star", "4.5 star", "4 star"],
              comment: ["Truly! Storage has never been so easy even for those with special space requirements. Spacious volumes and modular units extend the compositional options through geometries in motion that make your kitchen unique."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",


              },

              {
                category: "Kitchen Set",
              name: "Shine Kitchen Set 108",
              pricing: "₦6,250,000.00",
              description: "Making your kitchen all you want it to be, this design is a perfect blend of functionality and aesthetics. It offers ample storage solutions while maintaining a sleek and modern look. The modular units allow for flexibility in design, ensuring that your kitchen is not only beautiful but also practical.",
              image: ["https://baffihomeng.com/cdn/shop/files/1653.jpg?v=1720196667","https://baffihomeng.com/cdn/shop/files/1655.jpg?v=1720196668"],
              review:["5 star", "4.5 star", "4 star"],
              comment: ["Truly! Storage has never been so easy even for those with special space requirements. Spacious volumes and modular units extend the compositional options through geometries in motion that make your kitchen unique."],
              deliveryAndInstallation: "All deliveries of 700k and above is free within Abuja, Lagos, Kano and Enugu. Deliveries outside those cities are NOT FREE. All installation within Abuja, Lagos, Kano and Enugu is free, in case of installation outside those cities, the customer is responsible for our installers Logistics to and fro, Accommodation and Feeding for the period of his/her stay. Orders are delivered within 1-5a working days (Monday-Saturday) after payment approval. Depending on the distance and agreement made with the customer. Delivery times of special order production products is 14-21 working days depending on the product. We are not responsible for all deliveries outside Abuja, Lagos, Kano and Enugu, the customer and Cargo Company are responsible for such deliveries. Customer is to provide his/her phone number and delivery address clearly and a second phone number is highly recommended in case the customer cannot be reached. If a customer refuses to take delivery due to being not reachable or if a customer keeps our delivery team waiting for over an hour, in such cases the customer will be responsible for picking his/her items from our warehouse or showrooms. In case of Pre-Order products, delivery duration is 4-5 months unless otherwise specified to the customer.",
              },
            ]
          }


        ]
          

};

export default Data;